From 41d43e1ab71f2270341c9c29ecbae7eec4465030 Mon Sep 17 00:00:00 2001
From: SÃ©bastien Boyron <sboyron@redhat.com>
Date: Thu, 08 Oct 2020 16:19:39 +0200
Subject: [PATCH] Add catch for OSError and KeyError (PEP	3151)

During RPM packaging SUSE CI where raising KeyError and
OSError [0].

[0] https://review.opendev.org/755159

Change-Id: I47e25d3c70183e7617e42ac83a55f3d6e4f7a70f
---

diff --git a/tripleoclient/utils.py b/tripleoclient/utils.py
index 677e2bf..6955d4a 100644
--- a/tripleoclient/utils.py
+++ b/tripleoclient/utils.py
@@ -592,7 +592,7 @@
     get_uid = int(os.getenv('SUDO_UID', os.getuid()))
     try:
         user_pwd = pwd.getpwuid(get_uid)
-    except TypeError:
+    except (KeyError, TypeError):
         home = constants.CLOUD_HOME_DIR
     else:
         home = user_pwd.pw_dir
diff --git a/tripleoclient/v1/overcloud_netenv_validate.py b/tripleoclient/v1/overcloud_netenv_validate.py
index cd06acf..15f1b03 100644
--- a/tripleoclient/v1/overcloud_netenv_validate.py
+++ b/tripleoclient/v1/overcloud_netenv_validate.py
@@ -163,7 +163,7 @@
         try:
             with open(path, 'r') as nic_file:
                 nic_data = yaml.safe_load(nic_file)
-        except IOError:
+        except (IOError, OSError):
             self.log.error(
                 'The resource "%s" reference file does not exist: "%s"',
                 resource, path)
